#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S2,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Turning with Compass
This program instructs your robot turn until the desired number of degrees has been reached.
There is a two second pause at the beginning of the program.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor
Digital Port 5      compassSensor       Compass

----------------------------------------------------------------------------------------------------*/

// This program turns right for a specified 'degrees'

task main()
{
  wait1Msec(2000);
  int degrees = 90;                     // 'degrees' is how many degrees we want to turn

  int goal = (SensorValue[compassSensor] + degrees) % 360;  // 'goal' is be the current compassSensor reading + our turning degrees
                                                      /* We have to use modulus 360 to keep our goal within the bounds   */
                                                      /* of the compassSensor (1 to 360 degrees, 0 is 360).                    */

  while(SensorValue[compassSensor] != goal)   // while the compassSensor sensor reading is not yet our goal:
  {
										// turn RIGHT in place (point turn):
    motor[rightMotor] = -15;           	// set motorB to speed -15
    motor[leftMotor]  = 15;            	// set motorC to speed 15
  }
                                        // stop the robot:
  motor[rightMotor] = 0;                // set motorB to speed 0
  motor[leftMotor]  = 0;                // set motorC to speed 0
}
